In [123]:
import pandas as pd


column_names = [
    'CRIM', 
    'ZN', 
    'INDUS', 
    'CHAS', 
    'NOX', 
    'RM', 
    'AGE', 
    'DIS', 
    'RAD',
    'TAX', 
    'PTRATIO', 
    'B', 
    'LSTAT', 
    'MEDV'
]

df=pd.read_csv('BostonHousePrices/housing.csv', sep='[ ]+', names=column_names)
df.head()

C:\Users\symbi\AppData\Local\Temp\ipykernel_19528\2725566661.py:21: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  df=pd.read_csv('BostonHousePrices/housing.csv', sep='[ ]+', names=column_names)


CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  MEDV  
0     15.3  396.90   4.98  24.0  
1     17.8  396.90   9.14  21.6  
2     17.8  392.83   4.03  34.7  
3     18.7  394.63   2.94  33.4  
4     18.7  396.90   5.33  36.2

In [124]:
df.info()
df = df.astype('float')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64  
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64  
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       50

In [125]:
Y=df['MEDV']
del(df['MEDV'])

Y, df

(0      24.0
 1      21.6
 2      34.7
 3      33.4
 4      36.2
        ... 
 501    22.4
 502    20.6
 503    23.9
 504    22.0
 505    11.9
 Name: MEDV, Length: 506, dtype: float64,
         CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
 0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
 1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
 2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
 3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
 4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
 ..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
 501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
 502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
 503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
 504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2

In [126]:
from sklearn.model_selection import train_test_split

arr_df=df.to_numpy()
arr_y=Y.to_numpy()

X_train, X_test, y_train, y_test = train_test_split(arr_df, arr_y, random_state=1)

X_test

array([[4.9320e-02, 3.3000e+01, 2.1800e+00, ..., 1.8400e+01, 3.9690e+02,
        7.5300e+00],
       [2.5430e-02, 5.5000e+01, 3.7800e+00, ..., 1.7600e+01, 3.9690e+02,
        7.1800e+00],
       [2.2927e-01, 0.0000e+00, 6.9100e+00, ..., 1.7900e+01, 3.9274e+02,
        1.8800e+01],
       ...,
       [4.2970e-02, 5.2500e+01, 5.3200e+00, ..., 1.6600e+01, 3.7172e+02,
        9.5100e+00],
       [2.3912e-01, 0.0000e+00, 9.6900e+00, ..., 1.9200e+01, 3.9690e+02,
        1.2920e+01],
       [8.2650e-02, 0.0000e+00, 1.3920e+01, ..., 1.6000e+01, 3.9690e+02,
        8.5800e+00]])

In [127]:
import torch
X_train = torch.tensor(X_train, dtype=torch.float)
X_test = torch.tensor(X_test, dtype=torch.float)
y_train = torch.tensor(y_train, dtype=torch.float)
y_test = torch.tensor(y_test, dtype=torch.float)

print(type(X_train),
      type(X_test),
      type(y_train),
      type(y_test))

print(f'X_train.shape={X_train.shape}\n'
      f'X_test.shape= {X_test.shape}\n'
      f'y_train.shape={y_train.shape}\n'
      f'y_test.shape= {y_test.shape}\n')

<class 'torch.Tensor'> <class 'torch.Tensor'> <class 'torch.Tensor'> <class 'torch.Tensor'>
X_train.shape=torch.Size([379, 13])
X_test.shape= torch.Size([127, 13])
y_train.shape=torch.Size([379])
y_test.shape= torch.Size([127])



In [128]:
from torch.utils.data import TensorDataset, DataLoader

batch_size = 10
lr = 0.000001
num_epochs = 1000

dataset = TensorDataset(X_train, y_train)
data_iter = DataLoader(dataset, batch_size, shuffle=True)

for X, y in data_iter:
    print(X,'\n', y)
    break

tensor([[6.9622e+00, 0.0000e+00, 1.8100e+01, 0.0000e+00, 7.0000e-01, 5.7130e+00,
         9.7000e+01, 1.9265e+00, 2.4000e+01, 6.6600e+02, 2.0200e+01, 3.9443e+02,
         1.7110e+01],
        [2.9819e-01, 0.0000e+00, 6.2000e+00, 0.0000e+00, 5.0400e-01, 7.6860e+00,
         1.7000e+01, 3.3751e+00, 8.0000e+00, 3.0700e+02, 1.7400e+01, 3.7751e+02,
         3.9200e+00],
        [4.8190e-02, 8.0000e+01, 3.6400e+00, 0.0000e+00, 3.9200e-01, 6.1080e+00,
         3.2000e+01, 9.2203e+00, 1.0000e+00, 3.1500e+02, 1.6400e+01, 3.9289e+02,
         6.5700e+00],
        [3.9610e-02, 0.0000e+00, 5.1900e+00, 0.0000e+00, 5.1500e-01, 6.0370e+00,
         3.4500e+01, 5.9853e+00, 5.0000e+00, 2.2400e+02, 2.0200e+01, 3.9690e+02,
         8.0100e+00],
        [1.3428e+00, 0.0000e+00, 1.9580e+01, 0.0000e+00, 6.0500e-01, 6.0660e+00,
         1.0000e+02, 1.7573e+00, 5.0000e+00, 4.0300e+02, 1.4700e+01, 3.5389e+02,
         6.4300e+00],
        [4.6296e-01, 0.0000e+00, 6.2000e+00, 0.0000e+00, 5.0400e-01, 7.4120e+00,

In [129]:
model = torch.nn.Sequential(torch.nn.Linear(X_train.shape[-1], 1))
model.parameters

<bound method Module.parameters of Sequential(
  (0): Linear(in_features=13, out_features=1, bias=True)
)>

In [131]:
trainer = torch.optim.SGD(model.parameters(), lr=lr)
loss = torch.nn.MSELoss(reduction='mean')

for epoch in range(1, num_epochs + 1):
    for X, y in data_iter:
        trainer.zero_grad()
        l = loss(model(X).reshape(-1), y)
        l.backward()
        trainer.step()
    l = loss(model(X_train).reshape(-1), y_train)
    if epoch % 5 == 0:
        print('epoch %d, loss: %f' % (epoch, l.item()),'|\tw', model[0].weight.data, '|\tb', model[0].bias.data)

epoch 5, loss: 89.920174 |	w tensor([[-0.1310,  0.0249,  0.1156, -0.1868, -0.1278,  0.0706,  0.1102,  0.2462,
         -0.0756, -0.0165,  0.0968,  0.0445,  0.0683]]) |	b tensor([-0.2685])
epoch 10, loss: 88.263458 |	w tensor([[-0.1319,  0.0508,  0.1101, -0.1867, -0.1278,  0.0730,  0.0827,  0.2480,
         -0.0740, -0.0045,  0.0971,  0.0470,  0.0557]]) |	b tensor([-0.2684])
epoch 15, loss: 79.061546 |	w tensor([[-0.1328,  0.0701,  0.1055, -0.1865, -0.1278,  0.0752,  0.0626,  0.2492,
         -0.0727, -0.0009,  0.0974,  0.0442,  0.0442]]) |	b tensor([-0.2682])
epoch 20, loss: 71.921089 |	w tensor([[-0.1341,  0.0844,  0.1015, -0.1864, -0.1278,  0.0775,  0.0481,  0.2501,
         -0.0720, -0.0044,  0.0978,  0.0432,  0.0334]]) |	b tensor([-0.2681])
epoch 25, loss: 73.748390 |	w tensor([[-0.1350,  0.0949,  0.0981, -0.1862, -0.1278,  0.0798,  0.0376,  0.2508,
         -0.0711, -0.0055,  0.0984,  0.0431,  0.0232]]) |	b tensor([-0.2679])
epoch 30, loss: 70.262970 |	w tensor([[-0.1357,  0.1029,

In [132]:
w = model[0].weight.data
b = model[0].bias.data
w,b

(tensor([[-0.1076,  0.1104, -0.0287, -0.1588, -0.1158,  0.4327,  0.1075,  0.2529,
           0.0190,  0.0028,  0.2945,  0.0333, -0.6730]]),
 tensor([-0.2356]))

In [133]:
loss(model(X_test).reshape(-1), y_test)

tensor(55.2125, grad_fn=<MseLossBackward0>)